### PR TITLE
Pin build to debian 9, fix library paths

### LINKED ISSUE #5: build fail - cmake error: Unable to find the requested boost libraries
Attempting to do a default build. Fails on step 9/18 while running build_core.sh. Opening issue while i research / troubleshoot

```Removing intermediate container 315f26b526e0
Step 9/18 : RUN /etc/build_core.sh
 ---> Running in 6ffcb7782731
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmariadbclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git
-- 
    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* TrinityCore revision   : unknown 1970-01-01 00:00:00 +0000 (Archived branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /usr/local
* Install libraries to   : /usr/local/lib
* Install configs to     : /usr/local/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show all warnings      : Yes
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at cmake/macros/FindBoost.cmake:1204 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_system
          boost_filesystem
          boost_thread
          boost_program_options
          boost_iostreams
          boost_regex

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.  If you still have problems search on forum for TCE00020.
Call Stack (most recent call first):
  dep/boost/CMakeLists.txt:44 (find_package)


-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Failed
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.7/Modules/FindZLIB.cmake:114 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  dep/zlib/CMakeLists.txt:13 (find_package)


-- Configuring incomplete, errors occurred!
See also "/usr/local/trinitycore/TrinityCore/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/trinitycore/TrinityCore/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
The command '/bin/sh -c /etc/build_core.sh' returned a non-zero code: 2
```

### PR DESCRIPTION
**Pull request by kirbysayshi**
Fixes #5, at least on my machine!

Several problems here: when we did this two years ago, we used debian:latest, which of course is now a completely different OS version!

Also, it seems that debian:9 did something with library prefixes, causing all the cmake scripts to fail (boost was just the first failure, since it was in a subdir). Almost all the libraries failed to be found due to debian putting them into `/usr/lib/[arch]` instead of `/usr/lib/`.

The server is still compiling on my (old) machine, so not sure if there are other issues. But it's compiling, which is the good part.

@drewmullen as @josefalcon said in #5, this was basically just a weekend project with lots of rough edges. It wasn't too hard to fix these issues, but there are probably lots more lurking in the hacky scripts we wrote, especially with 2 years of TrinityCore development in the meantime!

### CODE REVIEW

**Comment by kirbysayshi** [comment]
Compiled successfully! Merging ✨ !

**Comment by josefalcon** [comment]
I'm glad you got this to work. I did basically the same thing in a branch but still got the "boost not found" errors. Does the order of the env variables matter with cmake? I did put the `BOOST_INCLUDEDIR` after the prefix, but I can't imagine that would affect anything.

**Comment by josefalcon** [comment]
This complied for me too!

**Comment by kirbysayshi** [comment]
The order of cmake variables shouldn't matter, but maybe there was a subtle
difference? I'd have to see what your other version looked like.

**Pull request merged**
